---
# Send a request for a simplified ui (without arrow fonts) to plugins

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
pane_frames: false

# Choose the theme that is specified in the themes section.
# For some examples, see: https://github.com/zellij-org/zellij/tree/main/example/themes
# Default: default
#theme: default

# Choose the mode that zellij uses when starting up.
# Default: normal
#default_mode: locked

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
#scroll_buffer_size: 10000

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
#copy_clipboard: primary

# Enable or disable automatic copy (and clear) of selection when releasing mouse
#copy_on_select: true

# Path to the default editor to use to edit pane scrollbuffer
# scrollback_editor: /usr/bin/nano

default_layout: compact
