---
# Send a request for a simplified ui (without arrow fonts) to plugins

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
pane_frames: false

# Choose the theme that is specified in the themes section.
# For some examples, see: https://github.com/zellij-org/zellij/tree/main/example/themes
# Default: default
#theme: default

# Choose the mode that zellij uses when starting up.
# Default: normal
#default_mode: locked

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
#scroll_buffer_size: 10000

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
#copy_clipboard: primary

# Enable or disable automatic copy (and clear) of selection when releasing mouse
#copy_on_select: true

# Path to the default editor to use to edit pane scrollbuffer
scrollback_editor: hx

default_layout: compact

themes:
  gruvbox-dark:
    bg: [40, 40, 40]
    red: [204, 36, 29]
    green: [152, 151, 26]
    yellow: [215, 153, 33]
    blue: [69, 133, 136]
    magenta: [177, 98, 134]
    orange: [214, 93, 14]
    fg: [213, 196, 161]
    cyan: [104, 157, 106]
    black: [60, 56, 54]
    white: [251, 241, 199]
  dracula:
    # From https://github.com/dracula/zellij
    bg: [40, 42, 54]
    red: [255, 85, 85]
    green: [80, 250, 123]
    yellow: [241, 250, 140]
    blue: [98, 114, 164]
    magenta: [255, 121, 198]
    orange: [255, 184, 108]
    fg: [248, 248, 242]
    cyan: [139, 233, 253]
    black: [0, 0, 0]
    white: [255, 255, 255]

theme: gruvbox-dark